name: CI

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run tests
          run: cargo test --verbose

    mutation-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install cargo mutations
          run: cargo install --locked cargo-mutants

        - name: Run mutation tests
          run: cargo mutants --jobs 2

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build
              run: cargo build --verbose